name: CI
on:
  pull_request:
  push:
    branches:
      - foxy-devel
  schedule:
    # every Monday
    - cron:  '0 0 * * 1'

jobs:
  build:
    runs-on: [windows-2019]
    strategy:
      fail-fast: false
      matrix:
        ROSDISTRO: [foxy]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        path: src
    - name: Install
      shell: cmd
      run: |
        choco sources add -n=roswin -s https://aka.ms/ros/public --priority 1
        choco install ros-%ROSDISTRO%-desktop -y --no-progress
      env:
        ROSDISTRO: ${{ matrix.ROSDISTRO }}
    - name: Install Azure Kinect Sensor SDK
      shell: powershell
      run: |
        wget https://download.microsoft.com/download/e/6/6/e66482b2-b6c1-4e34-bfee-95294163fc40/Azure%20Kinect%20SDK%201.3.0.exe -OutFile sdk.exe
        $p = Start-Process -PassThru -FilePath ".\sdk.exe" -Wait -NoNewWindow -ArgumentList "/passive"
        $p.WaitForExit()    
    - name: Build
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64 -host_arch=amd64
        call "C:\opt\ros\%ROSDISTRO%\x64\setup.bat"
        colcon build --packages-select azure_kinect_ros_driver --event-handlers console_cohesion+
      env:
        ROSDISTRO: ${{ matrix.ROSDISTRO }}
